steps:
 #Install node dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions'

# Run linting
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'lint']
  dir: 'functions'

# Deploy to Firebase
- name: 'gcr.io/cloud-resume-34b6d/firebase'
  args: ['deploy', '--token', '1//06MD93-L38HRXCgYIARAAGAYSNwF-L9IrPHMXx6gI2bh7oGQpFRd-JGs9yyhkqs53ij-UwUrJT89JNwttdx8Z-xYex86tBH4oqcc']
  secretEnv: ['1//06MD93-L38HRXCgYIARAAGAYSNwF-L9IrPHMXx6gI2bh7oGQpFRd-JGs9yyhkqs53ij-UwUrJT89JNwttdx8Z-xYex86tBH4oqcc']

secrets:
- kmsKeyName: projects/cloud-resume-34b6d/locations/global/keyRings/my-cloud-key
  secretEnv:
    _FIREBASE_TOKEN: MS8vMDZNRDkzLUwzOEhSWENnWUlBUkFBR0FZU053Ri1MOUlyUEhNWHg2Z0kyYmg3b0dRcEZSZC1KR3M5eXloa3FzNTNpai1Vd1VySlQ4OUpOd3R0ZHg4Wi14WWV4ODZ0Qkg0b3FjYw==
