steps:
 #Install node dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions'

# Run linting
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'lint']
  dir: 'functions'

# Build the functions
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'functions'

# Deploy to Firebase
- name: 'gcr.io/cloud-resume-34b6d/firebase'
  args: ['deploy', '--token', '$$ENCRYPTED_FIREBASE_TOKEN']
  secretEnv: ['ENCRYPTED_FIREBASE_TOKEN']

secrets:
- kmsKeyName: projects/cloud-resume-34b6d/locations/global/keyRings/my-cloud-key/cryptoKeys/my-cloud-key
  secretEnv:
    _FIREBASE_TOKEN: "[BASE64_ENCODED_ENCRYPTED_TOKEN]"
