steps:
# Install node dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions'

# Run linting
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'lint']
  dir: 'functions'

# Deploy to Firebase
# Note: this step requires the Firebase token to be stored as a Secret in Cloud Build
- name: 'gcr.io/cloud-resume-34b6d/firebase'
  args: ['deploy', '--token', '1//06XOJpJi3aCATCgYIARAAGAYSNwF-L9IrwBxMXlVegF5x7LCzd-AHh5Z69K4_XVkyjT44pKB7aeSLETED4n4DRLTYp45hzNIKVlA']
