name: Deploy to Firebase Functions on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./functions

      - name: Setup and verify Google Cloud credentials
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > /tmp/google-application-credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/google-application-credentials.json
          npx firebase-tools --version
          npx firebase-tools projects:list
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/google-application-credentials.json

      - name: Deploy to Firebase Functions
        run: |
          npx firebase-tools deploy --only functions --project cloud-resume-34b6d --debug
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/google-application-credentials.json
        working-directory: ./functions

      - name: List deployed functions
        run: |
          npx firebase-tools functions:list --project cloud-resume-34b6d
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/google-application-credentials.json