name: Deploy to Firebase Functions on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./functions
        
      - name: Lint
        run: npm run lint
        working-directory: ./functions

      # Replace the manual credential setup with Google's official action
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
          project_id: 'cloud-resume-34b6d'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Firebase Functions
        run: |
          npx firebase-tools deploy --only functions --project cloud-resume-34b6d
        working-directory: ./functions

      - name: List deployed functions
        run: |
          npx firebase-tools functions:list --project cloud-resume-34b6d